# Generated by Django 4.2.25 on 2025-10-08 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=200, null=True, verbose_name='Должность')),
                ('department', models.CharField(blank=True, max_length=200, null=True, verbose_name='Отдел')),
                ('business_center', models.CharField(blank=True, max_length=100, null=True, verbose_name='Бизнес-центр')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram username')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('coffee', '☕️ Тайный кофе'), ('lunch', '🍝 Обед вслепую'), ('walk', '🚶 Слепая прогулка'), ('chess', '♟️ Шахматы'), ('pingpong', '🏓 Настольный теннис'), ('games', '🎲 Настольные игры'), ('photo', '📸 Фотоквесты'), ('masterclass', '🧠 Мастер-классы'), ('clubs', '📚 Клубы по интересам')], max_length=20, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('emoji', models.CharField(max_length=10, verbose_name='Эмодзи')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Интерес',
                'verbose_name_plural': 'Интересы',
            },
        ),
        migrations.CreateModel(
            name='EmployeeInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='employees.employee')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.interest')),
            ],
            options={
                'verbose_name': 'Интерес сотрудника',
                'verbose_name_plural': 'Интересы сотрудников',
                'unique_together': {('employee', 'interest')},
            },
        ),
    ]
