# Generated by Django 4.2.25 on 2025-10-08 16:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('achievement_type', models.CharField(choices=[('participation', 'Участие'), ('consistency', 'Постоянство'), ('social', 'Социальная активность'), ('expert', 'Экспертность'), ('special', 'Особое достижение')], max_length=20, verbose_name='Тип достижения')),
                ('icon', models.CharField(default='🏆', max_length=50, verbose_name='Иконка')),
                ('condition_type', models.CharField(choices=[('count', 'Количество участий'), ('streak', 'Серия участий'), ('variety', 'Разнообразие активностей'), ('manual', 'Ручное назначение')], max_length=20, verbose_name='Тип условия')),
                ('condition_value', models.IntegerField(default=1, verbose_name='Значение условия')),
                ('condition_activity_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип активности для условия')),
                ('points_reward', models.IntegerField(default=10, verbose_name='Награда в баллах')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['achievement_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('activity_type', models.CharField(choices=[('coffee', 'Тайный кофе'), ('lunch', 'Обед вслепую'), ('walk', 'Слепая прогулка'), ('chess', 'Шахматы'), ('pingpong', 'Настольный теннис'), ('games', 'Настольные игры'), ('photo', 'Фотоквест'), ('masterclass', 'Мастер-класс'), ('club', 'Клуб по интересам')], max_length=20, verbose_name='Тип активности')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('scheduled_date', models.DateField(verbose_name='Дата проведения')),
                ('scheduled_time', models.TimeField(blank=True, null=True, verbose_name='Время проведения')),
                ('duration_minutes', models.IntegerField(default=30, verbose_name='Длительность (минут)')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланировано'), ('active', 'Активно'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='draft', max_length=20, verbose_name='Статус')),
                ('max_participants', models.IntegerField(default=2, verbose_name='Максимум участников')),
                ('is_auto_created', models.BooleanField(default=False, verbose_name='Авто-создано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Активность',
                'verbose_name_plural': 'Активности',
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='ActivityParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Приглашен'), ('confirmed', 'Подтвердил'), ('declined', 'Отказался'), ('attended', 'Присутствовал'), ('no_show', 'Не явился')], default='invited', max_length=20, verbose_name='Статус')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('feedback', models.TextField(blank=True, verbose_name='Отзыв')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='Приглашен')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Ответил')),
                ('attended_at', models.DateTimeField(blank=True, null=True, verbose_name='Присутствовал')),
            ],
            options={
                'verbose_name': 'Участник активности',
                'verbose_name_plural': 'Участники активностей',
            },
        ),
        migrations.CreateModel(
            name='BotAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_super_admin', models.BooleanField(default=False, verbose_name='Супер-администратор')),
                ('can_manage_users', models.BooleanField(default=True, verbose_name='Может управлять пользователями')),
                ('can_manage_activities', models.BooleanField(default=True, verbose_name='Может управлять активностями')),
                ('can_view_reports', models.BooleanField(default=True, verbose_name='Может просматривать отчеты')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
            ],
            options={
                'verbose_name': 'Администратор бота',
                'verbose_name_plural': 'Администраторы бота',
            },
        ),
        migrations.CreateModel(
            name='BusinessCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название БЦ')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Бизнес-центр',
                'verbose_name_plural': 'Бизнес-центры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название отдела')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код отдела')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Получено')),
                ('progress', models.FloatField(default=0.0, verbose_name='Прогресс')),
            ],
            options={
                'verbose_name': 'Достижение сотрудника',
                'verbose_name_plural': 'Достижения сотрудников',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='interest',
            options={'ordering': ['code'], 'verbose_name': 'Интерес', 'verbose_name_plural': 'Интересы'},
        ),
        migrations.AddField(
            model_name='employee',
            name='authorized',
            field=models.BooleanField(default=False, verbose_name='Авторизован'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приема на работу'),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность'),
        ),
        migrations.AddField(
            model_name='employee',
            name='normalized_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Нормализованный username'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='employeeinterest',
            name='notification_frequency',
            field=models.CharField(choices=[('immediate', 'Мгновенно'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно')], default='immediate', max_length=20, verbose_name='Частота уведомлений'),
        ),
        migrations.AddField(
            model_name='employeeinterest',
            name='receive_notifications',
            field=models.BooleanField(default=True, verbose_name='Получать уведомления'),
        ),
        migrations.AddField(
            model_name='employeeinterest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
        migrations.AddField(
            model_name='interest',
            name='auto_schedule',
            field=models.BooleanField(default=True, verbose_name='Авто-планирование'),
        ),
        migrations.AddField(
            model_name='interest',
            name='schedule_frequency',
            field=models.CharField(choices=[('weekly', 'Еженедельно'), ('biweekly', 'Раз в две недели'), ('monthly', 'Ежемесячно')], default='weekly', max_length=20, verbose_name='Частота'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['telegram_id'], name='employees_e_telegra_1dce9a_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['telegram_username'], name='employees_e_telegra_88e489_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['normalized_username'], name='employees_e_normali_408912_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_active', 'authorized'], name='employees_e_is_acti_572395_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeinterest',
            index=models.Index(fields=['employee', 'is_active'], name='employees_e_employe_862e38_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeinterest',
            index=models.Index(fields=['interest', 'is_active'], name='employees_e_interes_46a9a3_idx'),
        ),
        migrations.AddField(
            model_name='employeeachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.achievement'),
        ),
        migrations.AddField(
            model_name='employeeachievement',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='botadmin',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_admins', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='botadmin',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_admin', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='activityparticipant',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='employees.activity'),
        ),
        migrations.AddField(
            model_name='activityparticipant',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to='employees.employee', verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='activity',
            name='interest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.interest', verbose_name='Интерес'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='business_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.businesscenter', verbose_name='Бизнес-центр'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department', verbose_name='Отдел'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeachievement',
            unique_together={('employee', 'achievement')},
        ),
        migrations.AddIndex(
            model_name='activityparticipant',
            index=models.Index(fields=['activity', 'status'], name='employees_a_activit_6d0f92_idx'),
        ),
        migrations.AddIndex(
            model_name='activityparticipant',
            index=models.Index(fields=['employee', 'status'], name='employees_a_employe_af192b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activityparticipant',
            unique_together={('activity', 'employee')},
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type', 'status'], name='employees_a_activit_082d9c_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['scheduled_date', 'status'], name='employees_a_schedul_0e4d63_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['interest', 'status'], name='employees_a_interes_150698_idx'),
        ),
    ]
