# Generated by Django 4.2.25 on 2025-10-09 18:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_achievement_activity_activityparticipant_botadmin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretCoffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Понедельник недели, для которой создаются пары', verbose_name='Начало недели')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название сессии')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активная'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус')),
                ('max_pairs', models.IntegerField(default=50, help_text='Максимальное количество пар для сессии', verbose_name='Максимум пар')),
                ('algorithm_used', models.CharField(blank=True, help_text='Алгоритм, использованный для создания пар', max_length=50, verbose_name='Использованный алгоритм')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн регистрации')),
                ('meeting_deadline', models.DateField(blank=True, null=True, verbose_name='Дедлайн встреч')),
                ('total_participants', models.IntegerField(default=0, verbose_name='Всего участников')),
                ('successful_pairs', models.IntegerField(default=0, verbose_name='Успешных пар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coffee_sessions', to='employees.employee', verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Сессия тайного кофе',
                'verbose_name_plural': 'Сессии тайного кофе',
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='CoffeePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_employee1', models.BooleanField(default=False, verbose_name='Подтверждение от первого')),
                ('confirmed_employee2', models.BooleanField(default=False, verbose_name='Подтверждение от второго')),
                ('chat_created', models.BooleanField(default=False, verbose_name='Чат создан')),
                ('chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID чата')),
                ('meeting_scheduled', models.BooleanField(default=False, verbose_name='Встреча запланирована')),
                ('meeting_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата встречи')),
                ('meeting_place', models.CharField(blank=True, max_length=200, verbose_name='Место встречи')),
                ('meeting_completed', models.BooleanField(default=False, verbose_name='Встреча состоялась')),
                ('feedback_employee1', models.TextField(blank=True, verbose_name='Отзыв первого сотрудника')),
                ('feedback_employee2', models.TextField(blank=True, verbose_name='Отзыв второго сотрудника')),
                ('rating_employee1', models.IntegerField(blank=True, help_text='Оценка от 1 до 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка от первого')),
                ('rating_employee2', models.IntegerField(blank=True, help_text='Оценка от 1 до 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка от второго')),
                ('match_score', models.FloatField(default=0.0, help_text='Оценка алгоритма от 0 до 1', verbose_name='Оценка совместимости')),
                ('match_reason', models.TextField(blank=True, verbose_name='Причина объединения в пару')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('notified', 'Уведомления отправлены'), ('confirmed', 'Подтверждена'), ('meeting_scheduled', 'Встреча запланирована'), ('completed', 'Завершена'), ('declined', 'Отказались'), ('expired', 'Просрочена')], default='created', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Уведомления отправлены')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подтверждено')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('employee1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coffee_pairs_as_first', to='employees.employee', verbose_name='Первый сотрудник')),
                ('employee2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coffee_pairs_as_second', to='employees.employee', verbose_name='Второй сотрудник')),
                ('secret_coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coffee_pairs', to='employees.secretcoffee', verbose_name='Сессия тайного кофе')),
            ],
            options={
                'verbose_name': 'Пара для тайного кофе',
                'verbose_name_plural': 'Пары для тайного кофе',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='secretcoffee',
            index=models.Index(fields=['week_start', 'status'], name='employees_s_week_st_4e21bc_idx'),
        ),
        migrations.AddIndex(
            model_name='secretcoffee',
            index=models.Index(fields=['status', 'created_at'], name='employees_s_status_5a25fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='secretcoffee',
            unique_together={('week_start',)},
        ),
        migrations.AddIndex(
            model_name='coffeepair',
            index=models.Index(fields=['secret_coffee', 'status'], name='employees_c_secret__879174_idx'),
        ),
        migrations.AddIndex(
            model_name='coffeepair',
            index=models.Index(fields=['employee1', 'status'], name='employees_c_employe_23de8c_idx'),
        ),
        migrations.AddIndex(
            model_name='coffeepair',
            index=models.Index(fields=['employee2', 'status'], name='employees_c_employe_4b43ad_idx'),
        ),
        migrations.AddIndex(
            model_name='coffeepair',
            index=models.Index(fields=['status', 'created_at'], name='employees_c_status_6b1425_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coffeepair',
            unique_together={('secret_coffee', 'employee1', 'employee2')},
        ),
    ]
