# Generated by Django 4.2.25 on 2025-10-14 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_adminuser_adminlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Администратор', 'verbose_name_plural': 'Администраторы'},
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='action',
            field=models.CharField(choices=[('login', 'Вход в систему'), ('command', 'Выполнение команды'), ('manage', 'Управление объектом'), ('system', 'Системное действие'), ('error', 'Ошибка')], max_length=50, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='employees.adminuser', verbose_name='Администратор'),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='command',
            field=models.CharField(blank=True, max_length=100, verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='details',
            field=models.JSONField(default=dict, verbose_name='Детали'),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='target_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID объекта'),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='target_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='permissions',
            field=models.JSONField(blank=True, default=list, verbose_name='Права доступа'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Супер администратор'), ('admin', 'Администратор'), ('moderator', 'Модератор')], default='moderator', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AddIndex(
            model_name='adminlog',
            index=models.Index(fields=['admin', 'created_at'], name='admin_logs_admin_i_5f0f2e_idx'),
        ),
        migrations.AddIndex(
            model_name='adminlog',
            index=models.Index(fields=['action', 'created_at'], name='admin_logs_action_8ecf41_idx'),
        ),
        migrations.AddIndex(
            model_name='adminlog',
            index=models.Index(fields=['target_type', 'target_id'], name='admin_logs_target__bd5226_idx'),
        ),
    ]
