# Generated by Django 4.2.25 on 2025-10-11 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_add_secret_coffee_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('secret_coffee', 'Тайный кофе'), ('chess', 'Шахматы'), ('ping_pong', 'Настольный теннис'), ('photo_quest', 'Фотоквест'), ('workshop', 'Мастер-класс')], max_length=20)),
                ('week_start', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Запланирована'), ('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='planned', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'activity_sessions',
                'indexes': [models.Index(fields=['activity_type', 'week_start'], name='activity_se_activit_220781_idx'), models.Index(fields=['status'], name='activity_se_status_0c018c_idx')],
                'unique_together': {('activity_type', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='ActivityParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_status', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('activity_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='activities.activitysession')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_participations', to='employees.employee')),
            ],
            options={
                'db_table': 'activity_participants',
                'indexes': [models.Index(fields=['employee', 'subscription_status'], name='activity_pa_employe_87b16f_idx'), models.Index(fields=['activity_session', 'subscription_status'], name='activity_pa_activit_ad4d15_idx')],
                'unique_together': {('employee', 'activity_session')},
            },
        ),
        migrations.CreateModel(
            name='ActivityPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_created', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='activities.activitysession')),
                ('employee1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair1_activities', to='employees.employee')),
                ('employee2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair2_activities', to='employees.employee')),
            ],
            options={
                'db_table': 'activity_pairs',
                'indexes': [models.Index(fields=['activity_session', 'chat_created'], name='activity_pa_activit_36873c_idx')],
                'unique_together': {('activity_session', 'employee1', 'employee2')},
            },
        ),
    ]
