# Generated by Django 4.2.25 on 2025-10-11 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_add_secret_coffee_models'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretCoffeeMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('planned', 'Запланирована'), ('scheduling', 'В процессе планирования'), ('confirmed', 'Подтверждена'), ('completed', 'Завершена'), ('cancelled', 'Отменена'), ('failed', 'Не состоялась')], default='planned', max_length=15)),
                ('meeting_date', models.DateTimeField(blank=True, null=True)),
                ('meeting_location', models.CharField(blank=True, max_length=100)),
                ('meeting_format', models.CharField(choices=[('ONLINE', 'Онлайн'), ('OFFLINE', 'Оффлайн')], max_length=10)),
                ('employee1_code', models.CharField(max_length=20)),
                ('employee2_code', models.CharField(max_length=20)),
                ('recognition_sign', models.CharField(blank=True, max_length=50)),
                ('emergency_stopped', models.BooleanField(default=False)),
                ('moderator_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activitysession')),
                ('employee1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_coffee_initiator', to='employees.employee')),
                ('employee2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_coffee_partner', to='employees.employee')),
            ],
            options={
                'db_table': 'secret_coffee_meetings',
            },
        ),
        migrations.CreateModel(
            name='SecretCoffeeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_date', models.DateTimeField()),
                ('proposed_location', models.CharField(max_length=100)),
                ('proposed_format', models.CharField(choices=[('ONLINE', 'Онлайн'), ('OFFLINE', 'Оффлайн')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('accepted', 'Принято'), ('rejected', 'Отклонено'), ('countered', 'Предложен встречный вариант')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='activities.secretcoffeemeeting')),
            ],
            options={
                'db_table': 'secret_coffee_proposals',
            },
        ),
        migrations.CreateModel(
            name='SecretCoffeePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_slots', models.JSONField(default=list)),
                ('preferred_format', models.CharField(choices=[('ONLINE', 'Только онлайн'), ('OFFLINE', 'Только оффлайн'), ('BOTH', 'Оба формата')], default='BOTH', max_length=10)),
                ('office_location', models.CharField(blank=True, max_length=50)),
                ('topics_of_interest', models.JSONField(default=list)),
                ('avoid_specific_people', models.JSONField(default=list)),
                ('allow_photo_sharing', models.BooleanField(default=False)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coffee_preferences', to='employees.employee')),
            ],
            options={
                'db_table': 'secret_coffee_preferences',
            },
        ),
        migrations.CreateModel(
            name='SecretCoffeeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Текст'), ('proposal', 'Предложение встречи'), ('confirmation', 'Подтверждение'), ('photo', 'Фото'), ('emergency', 'Экстренное сообщение')], max_length=20)),
                ('content', models.TextField()),
                ('is_forwarded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='activities.secretcoffeemeeting')),
            ],
            options={
                'db_table': 'secret_coffee_messages',
                'indexes': [models.Index(fields=['meeting', 'created_at'], name='secret_coff_meeting_379f56_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='secretcoffeemeeting',
            index=models.Index(fields=['meeting_id'], name='secret_coff_meeting_fbbe45_idx'),
        ),
        migrations.AddIndex(
            model_name='secretcoffeemeeting',
            index=models.Index(fields=['status'], name='secret_coff_status_694553_idx'),
        ),
        migrations.AddIndex(
            model_name='secretcoffeemeeting',
            index=models.Index(fields=['meeting_date'], name='secret_coff_meeting_864650_idx'),
        ),
    ]
