# Generated by Django 4.2.25 on 2025-10-19 19:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_adminuser_options_alter_adminlog_action_and_more'),
        ('activities', '0002_secretcoffeemeeting_secretcoffeeproposal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretcoffeemeeting',
            name='average_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Средний рейтинг'),
        ),
        migrations.AddField(
            model_name='secretcoffeemeeting',
            name='feedback_collected',
            field=models.BooleanField(default=False, verbose_name='Сбор отзывов завершен'),
        ),
        migrations.AddField(
            model_name='secretcoffeemeeting',
            name='feedback_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн для отзывов'),
        ),
        migrations.CreateModel(
            name='MeetingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Оценка от 1 до 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('anonymous_feedback', models.TextField(blank=True, verbose_name='Анонимный отзыв')),
                ('suggestions', models.TextField(blank=True, verbose_name='Предложения')),
                ('feedback_type', models.CharField(choices=[('coffee', 'Тайный кофе'), ('chess', 'Шахматы'), ('pingpong', 'Настольный теннис'), ('workshop', 'Мастер-класс'), ('photo_quest', 'Фотоквест')], default='coffee', max_length=20, verbose_name='Тип отзыва')),
                ('is_anonymous', models.BooleanField(default=True, verbose_name='Анонимно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to='employees.employee', verbose_name='Сотрудник')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='activities.secretcoffeemeeting', verbose_name='Встреча')),
            ],
            options={
                'verbose_name': 'Отзыв о встрече',
                'verbose_name_plural': 'Отзывы о встречах',
                'db_table': 'meeting_feedback',
                'ordering': ['-created_at'],
                'unique_together': {('meeting', 'employee')},
            },
        ),
    ]
