# config/prometheus/prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'connectbot'
    static_configs:
      - targets: ['host.docker.internal:8000'] # Django-приложение
    metrics_path: /metrics
