version: '3.8'

secrets:
  django_secret_key:
    external: true
  service_auth_token:
    external: true
  telegram_bot_token:
    external: true

networks:
  app-net:
    driver: overlay
    name: connectbot-net
    attachable: true

services:
  redis:
    image: redis:alpine
    networks:
      - app-net

  web:
    image: alexom12/connectbot-web:final-fix
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    secrets:
      - django_secret_key
      - service_auth_token
      - telegram_bot_token
    depends_on:
      - redis
    networks:
      - app-net

  matching-service:
    image: alexom12/connectbot-matching-service:latest
    secrets:
      - service_auth_token
    depends_on:
      - web
    networks:
      - app-net
