services:
  redis:
    image: redis:7-alpine
    container_name: connectbot-v21-redis
    restart: always
    ports:
      - "6379:6379"

  matching-service:
    image: alexone1123/connectbot-matching-service:latest
    container_name: connectbot-v21-matching-service
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ./service_auth_token.txt:/run/secrets/service_auth_token:ro
    environment:
      SPRING_DATASOURCE_URL: "jdbc:h2:mem:testdb"
      SERVICE_AUTH_TOKEN_FILE: "/run/secrets/service_auth_token"
      DATAAPI_BASE_URL: "http://web:8000"
      DATAAPI_SERVICE_TOKEN_FILE: "/run/secrets/service_auth_token"

  web:
    image: alexone1123/connectbot-web:latest
    container_name: connectbot-v21-web
    restart: always
    command: bash -c "python manage.py collectstatic --noinput && gunicorn --chdir /app config.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/data
      - ./service_auth_token.txt:/run/secrets/service_auth_token:ro
      - ./telegram_bot_token.txt:/run/secrets/telegram_bot_token:ro
      - ./telegram_bot_token_dev.txt:/run/secrets/telegram_bot_token_dev:ro
      - ./django_secret_key.txt:/run/secrets/django_secret_key:ro
    environment:
      DEBUG: "0"
      DATABASE_URL: "sqlite:////app/data/db.sqlite3"
      MATCHING_SERVICE_URL: "http://matching-service:8081"
      REDIS_URL: "redis://redis:6379/0"
      DJANGO_SECRET_KEY_FILE: "/run/secrets/django_secret_key"
      SERVICE_AUTH_TOKEN_FILE: "/run/secrets/service_auth_token"
      TELEGRAM_BOT_TOKEN_FILE: "/run/secrets/telegram_bot_token"
    depends_on:
      - redis
      - matching-service

  bot:
    image: alexone1123/connectbot-bot:latest
    container_name: connectbot-v21-bot
    restart: always
    command: python manage.py runbot
    volumes:
      - sqlite_data:/app/data
      - ./service_auth_token.txt:/run/secrets/service_auth_token:ro
      - ./telegram_bot_token.txt:/run/secrets/telegram_bot_token:ro
      - ./telegram_bot_token_dev.txt:/run/secrets/telegram_bot_token_dev:ro
      - ./django_secret_key.txt:/run/secrets/django_secret_key:ro
    environment:
      DEBUG: "0"
      DATABASE_URL: "sqlite:////app/data/db.sqlite3"
      MATCHING_SERVICE_URL: "http://matching-service:8081"
      REDIS_URL: "redis://redis:6379/0"
      DJANGO_SECRET_KEY_FILE: "/run/secrets/django_secret_key"
      SERVICE_AUTH_TOKEN_FILE: "/run/secrets/service_auth_token"
      TELEGRAM_BOT_TOKEN_FILE: "/run/secrets/telegram_bot_token"
    depends_on:
      - redis
      - web

  prometheus:
    image: prom/prometheus:latest
    container_name: connectbot-v21-prometheus
    restart: always
    ports:
      - "9090:9090"

volumes:
  sqlite_data:


networks:
  default:
    driver: bridge
