version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  matching-service:
    build:
      context: ./connectbot-java-services/matching-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb

  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app:delegated
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - MATCHING_SERVICE_URL=http://matching-service:8081
      - REDIS_URL=redis://redis:6379/0
      - METRICS_TRIGGER_TOKEN=${METRICS_TRIGGER_TOKEN}
    depends_on:
      - matching-service
      - redis

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - web
      - matching-service

networks:
  default:
    driver: bridge
