version: '3.8'

networks:
  default:
    driver: overlay
    attachable: true

services:
  redis:
    image: redis:alpine
    networks:
      - default

  web:
    image: alexom12/connectbot-web:latest
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    secrets:
      - django_secret_key
      - service_auth_token
      - telegram_bot_token
    depends_on:
      - redis
    networks:
      - default

  debug:
    image: alpine:latest
    command: ["sleep", "3600"]
    networks:
      - default

secrets:
  django_secret_key:
    external: true
  service_auth_token:
    external: true
  telegram_bot_token:
    external: true
