version: '3.8'

services:
  matching-service:
    secrets:
      - service_auth_token
    environment:
      # read token from file inside container
      DATAAPI_SERVICE_TOKEN_FILE: /run/secrets/service_auth_token

  web:
    secrets:
      - django_secret_key
      - service_auth_token
    environment:
      DJANGO_SECRET_KEY_FILE: /run/secrets/django_secret_key
      SERVICE_AUTH_TOKEN_FILE: /run/secrets/service_auth_token

secrets:
  service_auth_token:
    external: true
  django_secret_key:
    external: true
  telegram_bot_token:
    external: true
