global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['web:8000']

  # You can add Java actuator metrics if exposed by the matching-service
  - job_name: 'matching-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['matching-service:8081']
