name: ConnectBot CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-python-app:
    name: Test Python (Django) Application
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django Tests
      run: |
        # Создаем фиктивный .env, чтобы тесты могли запуститься
        echo "SECRET_KEY=dummy-secret-key-for-ci" > .env
        echo "REDIS_URL=redis://localhost:6379/0" >> .env
        python manage.py test

  test-java-app:
    name: Test Java (Spring Boot) Service
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Make mvnw executable
      run: chmod +x connectbot-java-services/matching-service/mvnw

    - name: Run Java Tests
      run: |
        cd connectbot-java-services/matching-service
        ./mvnw test

  deploy:
    name: Deploy to Production Server
    needs: [test-python-app, test-java-app] # Запускать только после успешных тестов
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Запускать только для ветки main

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/ConnectBot-v21
          git pull origin main
          export TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
          export DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
          export SERVICE_AUTH_TOKEN=${{ secrets.SERVICE_AUTH_TOKEN }}
          bash scripts/run-on-server.sh
